services:

    _defaults:
        autowire: true
        autoconfigure: true
        
    OSW3\Faq\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'

    OSW3\Faq\EventSubscriber\TableNameSubscriber:
        tags: [{ name: doctrine.event_listener, event: loadClassMetadata }]